In [2]:
import numpy as np 
from scipy.linalg import expm

In [5]:
def setSimpleRateMatrix(mu, dim):
    #Initialize an empty matrix with dimensions given by user 
    a = np.empty([dim, dim])
    #fill matrix with value of mu
    a.fill(mu)
    #rate of UU and YY
    np.fill_diagonal(a, 1.0-(dim-1)*mu)
    #return rate matrix 
    return a 

In [22]:
def prob(t, R):
    #Set up identity matrix. Identity matrix are always square
    I = np.identity(R.shape[0]) #slice into the first dimension of R
    #display I
    print("Identity matrix\n",I,"\n")    
    #calculate the probability
    Q = (R - I) * t
    #call simpy func
    a = expm(Q)
    #return probability matrix 
    return a  

In [24]:
#initialize mu and time
mu = 0.01
t = 10000

#call setSimpleRateMatrix to create rate matrix
b = setSimpleRateMatrix(mu,2)
print("Rate Matrix\n",b,"\n")

#call prob to calculate poisson probability and matrix
p = prob(t, b)
print("prob(t)\n",p)

Rate Matrix
 [[0.99 0.01]
 [0.01 0.99]] 

Identity matrix
 [[1. 0.]
 [0. 1.]] 

prob(t)
 [[0.5 0.5]
 [0.5 0.5]]
