In [2]:
import numpy as np 
from scipy.linalg import expm

In [5]:
def setSimpleRateMatrix(mu, dim):
    a = np.empty([dim, dim])
    a.fill(mu)
    np.fill_diagonal(a, 1.0-(dim-1)*mu)
    return a 

In [7]:
mu = 0.01
b = setSimpleRateMatrix(mu,4)
print(b)

[[0.97 0.01 0.01 0.01]
 [0.01 0.97 0.01 0.01]
 [0.01 0.01 0.97 0.01]
 [0.01 0.01 0.01 0.97]]
